name: kafka-kerberos
services:
  krb5-kdc-server:
    image: godatadriven/krb5-kdc-server
    hostname: krb5-kdc-server
    volumes:
      - ./krb5-kdc-server/start_kdc.sh:/app/start_kdc.sh
      - ./krb5:/krb5
    ports:
      - "88:88"
      - "749:749"
  kafka:
    image: confluentinc/cp-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://kafka-kerberos-kafka-1.kafka-kerberos_default:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: SASL_PLAINTEXT:SASL_PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: SASL_PLAINTEXT
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: GSSAPI
      KAFKA_SASL_ENABLED_MECHANISMS: GSSAPI
      KAFKA_SASL_KERBEROS_SERVICE_NAME: kafka
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf -Djava.security.krb5.conf=/krb5/krb5.conf"
    volumes:
      - ./kafka/kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf
      - ./kafka/entry.sh:/entry.sh
      - ./krb5:/krb5
      - kafka_data:/var/lib/kafka/data
    entrypoint: ["/bin/bash", "-c", "/entry.sh"]
    depends_on:
      - krb5-kdc-server
      - zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookkeeper_logs:/var/lib/zookeeper/log
      - ./krb5:/krb5
      - ./zookeeper/zookeeper_jaas.conf:/etc/kafka/zookeeper_jaas.conf
      - ./zookeeper/entry.sh:/entry.sh
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_AUTHPROVIDER_1: org.apache.zookeeper.server.auth.SASLAuthenticationProvider
      ZOOKEEPER_KERBEROS_REMOVEHOSTFROMPRINCIPAL: true
      ZOOKEEPER_KERBEROS_REMOVEREALMFROMPRINCIPAL: true
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/zookeeper_jaas.conf -Dsun.security.krb5.debug=true -Djava.security.krb5.conf=/krb5/krb5.conf"
    depends_on:
      - krb5-kdc-server
    entrypoint: ["/bin/bash", "-c", "/entry.sh"]
#    command: ["bash", "-c", "trap : TERM INT; sleep infinity & wait"]
#    command: ["cp", "/krb5/krb5.keytab", "/home/appuser/krb5.keytab", ";", "/usr/bin/zookeeper-server-start.sh", "/etc/kafka/zookeeper.properties"]
volumes:
  zookeeper_data:
  zookkeeper_logs:
  kafka_data:
      